name: flutter_simple_animations
description: Flutter package that provides easy to use widgets for some of the most used simple animations.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.xn--grtner-bua.flutter_simple_animations
        pluginClass: FlutterSimpleAnimationsPlugin
      ios:
        pluginClass: FlutterSimpleAnimationsPlugin
      linux:
        pluginClass: FlutterSimpleAnimationsPlugin
      macos:
        pluginClass: FlutterSimpleAnimationsPlugin
      windows:
        pluginClass: FlutterSimpleAnimationsPluginCApi
